AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Incentives Currency Converter

Resources:
  DynamoDBRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: YatishDynamoDBRole
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: YatishDynamoDBPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: dynamodb:*
                Resource: '*'

  CurrencyDetailsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: currency-converter-details
      AttributeDefinitions:
        - AttributeName: currencyCode
          AttributeType: S
      KeySchema:
        - AttributeName: currencyCode
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Application
          Value: Incentives-Assignment

  UserDetailsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: user-login-credentials
      AttributeDefinitions:
        - AttributeName: emailId
          AttributeType: S
      KeySchema:
        - AttributeName: emailId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Application
          Value: Incentives-Assignment

  UserSessionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: user-session-tracker
      AttributeDefinitions:
        - AttributeName: sessionId
          AttributeType: S
      KeySchema:
        - AttributeName: sessionId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: expiresAt
        Enabled: true
      Tags:
        - Key: Application
          Value: Incentives-Assignment
